### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by prabuddhg** [vzhong/corenlp-docker#2]
Hi,

This may not a be an issue.

Prabuddhs-Air:CoreNLP pg$ docker run -p 9000:9000 vzhong/corenlp-server

 and in another terminal, i ran this command 

"curl --data 'A rather short sentence.' http://localhost:9000" and I see the results on my browser. Is it possible to get this information in text/json file?

**Comment by vzhong** [comment]
sorry I don't quite understand what you mean by this. `curl` should not open your browser right?

**Comment by vzhong** [comment]
Ah I think I understand what you meant. You are seeing HTML output instead of JSON. This is a corenlp server thing, which you can find [here](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html). In particular, you are missing the `properties` flag.

For example:

```
wget --post-data 'The quick brown fox jumped over the lazy dog.' 'localhost:9000/?properties={"annotators":"tokenize,ssplit,pos","outputFormat":"json"}' -O -
```
